// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.ShortCodeGenerator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("codes")]
        public string[] Codes { get; set; }

        [JsonProperty("count")]
        public long Count { get; set; }

        [JsonProperty("length")]
        public long Length { get; set; }

        [JsonProperty("charset")]
        public string Charset { get; set; }

        [JsonProperty("url_safe")]
        public bool UrlSafe { get; set; }
    }
}
